name: documentation

on:
  push:
    branches: ["main", "dev"]

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - uses: ./.github/actions/setup

    - name: Generate .rst files from package
      run: |
        sphinx-apidoc -o docs/source/api diabayes

    - name: Build Sphinx HTML documentation
      run: |
        cd docs
        make clean && make html

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: sphinx-html
        path: docs/build/html

    # Publish built docs to gh-pages branch
    - name: Commit documentation changes
      run: |
        git clone https://${{ secrets.GH_TOKEN }}@github.com/martijnende/diabayes.git --branch gh-pages --single-branch gh-pages
        cd gh-pages
        git clean -fdx  # Remove old untracked files and directories
        cp -r ../docs/build/html/* .  # Copy new HTML files to gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
      env:
        GH_PAT: ${{ secrets.GH_TOKEN }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        GH_PAT: ${{ secrets.GH_TOKEN }}